import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./reset.css";
import { ReactNode } from "react";
import NavigationBar from "./NavigationBar";
import ReactQueryProvider from "./_component/ReactQueryProvider";
import { AuthProvider } from "@/entities/auth/ui/AuthGuard";
import AuthLogger from "@/entities/auth/ui/AuthLogger";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// server.listen(); TODO : msw 사용할지말지 결정

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}

function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <AuthProvider>
        <AuthLogger>
          <ReactQueryProvider>
            <div className="drawer-content flex flex-col">
              <NavigationBar />
              {children}
            </div>
            <div id="modal"></div>
          </ReactQueryProvider>
        </AuthLogger>
      </AuthProvider>
    </>
  );
}
